import { UNTITLED_CHAPTER, TRASH_RETENTION_DAYS, TRASH_RETENTION_MS } from "@smudge/shared";

export const STRINGS = {
  app: {
    name: "Smudge",
  },
  project: {
    createNew: "New Project",
    titlePlaceholder: "Project title",
    fiction: "Fiction",
    nonfiction: "Non-fiction",
    modeLabel: "Project type",
    createButton: "Create",
    cancelButton: "Cancel",
    emptyState: "No projects yet. Create one to start writing.",
    emptyChapters: "No chapters yet. Add one to start writing.",
    wordCount: (count: number) => `${count.toLocaleString()} words`,
    lastEdited: (dateStr: string) => {
      const date = new Date(dateStr);
      return `Edited ${date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
    },
    lastDeleted: (dateStr: string) => {
      const date = new Date(dateStr);
      return `Deleted ${date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
    },
  },
  chapter: {
    untitledDefault: UNTITLED_CHAPTER,
  },
  delete: {
    buttonLabel: "Delete",
    deleteChapterAriaLabel: (title: string) => `Delete chapter ${title}`,
    deleteProjectAriaLabel: (title: string) => `Delete project ${title}`,
    confirmTitle: (name: string) => `Move \u201c${name}\u201d to trash?`,
    confirmBody: `You can restore it within ${TRASH_RETENTION_DAYS} days.`,
    confirmButton: "Confirm",
    cancelButton: "Cancel",
  },
  error: {
    projectNotFound: "Project not found",
    backToProjects: "Back to Projects",
    loadFailed: "Failed to load projects",
    loadProjectFailed: "Failed to load project",
    createFailed: "Failed to create project",
    createChapterFailed: "Failed to create chapter",
    loadChapterFailed: "Failed to load chapter",
    deleteChapterFailed: "Failed to delete chapter",
    reorderFailed: "Failed to reorder chapters",
    updateTitleFailed: "Failed to update project title",
    renameChapterFailed: "Failed to rename chapter",
    deleteFailed: "Failed to delete project",
    loadTrashFailed: "Failed to load trash",
    restoreChapterFailed: "Failed to restore chapter",
    loadDashboardFailed: "Failed to load dashboard",
    statusChangeFailed: "Failed to update chapter status",
    statusesFetchFailed: "Failed to load chapter statuses — status changes unavailable",
    settingsUpdateFailedGeneric: "Unable to save settings.",
  },
  editor: {
    placeholder: "Start writing\u2026",
    saving: "Saving\u2026",
    saved: "Saved",
    unsaved: "Unsaved changes",
    saveFailed: "Unable to save \u2014 check connection",
    saveFailedInvalid:
      "Unable to save \u2014 the chapter content is invalid. Undo recent changes or reload the page.",
    saveFailedTooLarge:
      "Unable to save \u2014 the chapter is too large. Split it into shorter chapters before continuing.",
    cacheUnavailable: "Local backup unavailable",
    viewSwitchSaveFailed:
      "Unable to save pending changes. Try again once your connection recovers before switching views.",
    mutationBusy: "Another operation is in progress — please wait.",
    lockedRefusal: "The editor is locked — refresh the page before continuing.",
    refreshButton: "Refresh page",
  },
  shortcuts: {
    dialogTitle: "Keyboard Shortcuts",
    togglePreview: "Toggle preview",
    newChapter: "New chapter",
    toggleSidebar: "Toggle sidebar",
    showShortcuts: "Keyboard shortcuts",
    prevChapter: "Previous chapter",
    nextChapter: "Next chapter",
    announceWordCount: "Announce word count",
    keyTogglePreview: "Ctrl+Shift+P",
    keyNewChapter: "Ctrl+Shift+N",
    keyToggleSidebar: "Ctrl+Shift+\\",
    keyPrevChapter: "Ctrl+Shift+\u2191",
    keyNextChapter: "Ctrl+Shift+\u2193",
    keyAnnounceWordCount: "Ctrl+Shift+W",
    keyShowShortcuts: "Ctrl+/",
    save: "Save now",
    keySave: "Ctrl+S",
    toggleReferencePanel: "Toggle reference panel",
    keyToggleReferencePanel: "Ctrl+.",
    findReplace: "Find and replace",
    keyFindReplace: "Ctrl+H",
  },
  sidebar: {
    addChapter: "Add Chapter",
    trash: "Trash",
    trashEmpty: "No chapters in trash.",
    restore: "Restore",
    permanentDeleteDate: (deletedAt: string) => {
      const purgeDate = new Date(new Date(deletedAt).getTime() + TRASH_RETENTION_MS);
      return `Permanently deleted ${purgeDate.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
    },
    backToEditor: "Back to editor",
    dragHandle: "Drag to reorder",
    chapterPosition: (title: string, position: number, total: number) =>
      `Chapter \u201c${title}\u201d moved to position ${position} of ${total}`,
    statusLabel: (label: string) => `Chapter status: ${label}`,
    statusChanged: (label: string) => `Chapter status changed to ${label}`,
    resizeHandle: "Resize sidebar",
    navigatedToChapter: (title: string) => `Navigated to ${title}`,
  },
  preview: {
    backToEditor: "Back to Editor",
    tableOfContents: "Table of Contents",
    renderError: "Unable to render content",
  },
  a11y: {
    mainContent: "Main content",
    chaptersSidebar: "Chapters",
    formattingToolbar: "Formatting",
    chapterTitleInput: "Chapter title",
    projectTitleInput: "Project title",
    editorContent: "Chapter content",
    dismissError: "Dismiss error",
    dismissInfo: "Dismiss info",
    viewModesNav: "View modes",
  },
  toolbar: {
    bold: "Bold",
    italic: "Italic",
    heading1: "H3",
    heading2: "H4",
    heading3: "H5",
    quote: "Quote",
    bulletList: "List",
    numberedList: "Numbered",
    horizontalRule: "HR",
  },
  home: {
    projectsHeading: "Projects",
  },
  nav: {
    backToProjects: "\u2190 Projects",
    preview: "Preview",
    editor: "Editor",
    dashboard: "Dashboard",
    loading: "Loading...",
    totalSuffix: "total",
  },
  dashboard: {
    heading: "Manuscript Dashboard",
    totalWordCount: (count: number) => `${count.toLocaleString()} words`,
    totalChapters: (count: number) => `${count} ${count === 1 ? "chapter" : "chapters"}`,
    mostRecentEdit: (dateStr: string, title: string) => {
      const date = new Date(dateStr);
      return `Most recent: ${date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} (${title})`;
    },
    leastRecentEdit: (dateStr: string, title: string) => {
      const date = new Date(dateStr);
      return `Least recent: ${date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} (${title})`;
    },
    emptyState: "No chapters yet",
    columnOrder: "#",
    columnTitle: "Title",
    columnStatus: "Status",
    columnWordCount: "Word Count",
    columnLastEdited: "Last Edited",
    healthSectionLabel: "Manuscript health",
    statusSummaryLabel: "Status summary",
    statusDistributionLabel: "Chapter status distribution",
    sortAscending: " \u2191",
    sortDescending: " \u2193",
  },
  velocity: {
    progressLabel: "Writing progress",
    emptyState: "Start writing to see your progress.",
    loadError: "Unable to load progress data.",
    dailyAverage: (count: number) => `Recent pace: ${count.toLocaleString()}/day`,
    requiredPace: (count: number) => `Needed pace: ${count.toLocaleString()}/day`,
    daysRemaining: (count: number) => `${count} ${count === 1 ? "day" : "days"} left`,
    deadlineReached: "Deadline reached",
    wordsOfTarget: (current: number, target: number) =>
      `${current.toLocaleString()} / ${target.toLocaleString()} words`,
    wordsTotal: (count: number) => `${count.toLocaleString()} words`,
    wordsToday: (count: number) => `${count.toLocaleString()} words today`,
    projectedDate: (date: string) => {
      const d = new Date(date + "T00:00:00Z");
      return `Projected: ${d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" })}`;
    },
  },
  settings: {
    heading: "Settings",
    timezoneLabel: "Timezone",
    save: "Save",
    cancel: "Cancel",
    saveError: "Failed to save settings. Please try again.",
  },
  projectSettings: {
    heading: "Project Settings",
    openLabel: "Open project settings",
    wordCountTarget: "Word count target",
    deadline: "Deadline",
    clear: "Clear",
    close: "Close",
    wordCountPlaceholder: "e.g. 80000",
    authorName: "Author name",
    authorNamePlaceholder: "e.g. Jane Doe",
    saveError: "Failed to save. Please try again.",
  },
  export: {
    buttonLabel: "Export",
    dialogTitle: "Export Manuscript",
    formatLabel: "Format",
    formatHtml: "HTML",
    formatMarkdown: "Markdown",
    formatPlainText: "Plain Text",
    formatDocx: "Word (.docx)",
    formatEpub: "EPUB",
    includeTocLabel: "Include table of contents",
    chapterSelectionAll: "All chapters",
    chapterSelectionChoose: "Select specific chapters...",
    exportButton: "Export",
    exportingButton: "Exporting...",
    cancelButton: "Cancel",
    success: (title: string) => `Exported "${title}"`,
    errorFailed: "Export failed. Please try again.",
    close: "Close export dialog",
    epubCoverImageLabel: "Cover image",
    epubCoverImageNone: "None",
    docxWebpWarning: "Some images use WebP format, which may not display in Word 2016 or earlier.",
  },
  referencePanel: {
    ariaLabel: "Reference panel",
    resizeHandle: "Resize reference panel",
    toggleTooltip: "Toggle reference panel (Ctrl+.)",
    imagesTab: "Images",
  },
  imageGallery: {
    uploadButton: "Upload image",
    noImages: "No images yet. Upload one to get started.",
    unusedBadge: "unused",
    noAltText: "No alt text",
    altTextLabel: "Alt text",
    captionLabel: "Caption",
    sourceLabel: "Source",
    licenseLabel: "License",
    saveButton: "Save",
    insertButton: "Insert at cursor",
    deleteButton: "Delete",
    backToGrid: "Back to gallery",
    deleteConfirm: "Delete this image?",
    deleteBlocked: (chapters: string[]) =>
      `This image is used in: ${chapters.join(", ")}. Remove it from those chapters first.`,
    deleteBlockedPrefix: "This image is used in:",
    deleteBlockedSuffix: "Remove it from those chapters first.",
    uploadSuccess: (filename: string) => `Image uploaded: ${filename}`,
    uploadFailed: (reason: string) => `Upload failed: ${reason}`,
    insertSuccess: (filename: string) => `Image inserted: ${filename}`,
    usedInChapters: "Used in",
    saving: "Saving...",
    saved: "Saved",
    fileTooLarge: "File too large. Maximum: 10MB.",
    deleteSuccess: (filename: string) => `Image deleted: ${filename}`,
    deleteFailed: (reason: string) => `Delete failed: ${reason}`,
    saveFailed: "Save failed. Your changes have not been saved.",
    deleteBlockedLoading: "This image is in use. Loading details...",
    inTrash: "in trash",
    loadFailed: "Failed to load images.",
    retryButton: "Retry",
    uploadFailedGeneric: "Upload failed. Check your connection and try again.",
    deleteFailedGeneric: "Delete failed. Try again.",
    deleteBlockedInUse: "This image is in use. Remove it from those chapters first.",
  },
  snapshots: {
    panelTitle: "Snapshots",
    toolbarLabel: (count: number | null) =>
      count != null && count > 0 ? `Snapshots (${count})` : "Snapshots",
    createButton: "Create Snapshot",
    labelPlaceholder: "Optional label (e.g., 'before major rewrite')",
    save: "Save",
    cancel: "Cancel",
    untitled: "Untitled snapshot",
    auto: "auto",
    view: "View",
    delete: "Delete",
    deleteConfirm: "Delete this snapshot? This cannot be undone.",
    deleteConfirmButton: "Delete",
    deleteCancel: "Cancel",
    restoreButton: "Restore",
    actionsUnavailableWhileLocked:
      "Unavailable — the editor is locked. Refresh the page before continuing.",
    restoreConfirm:
      "Replace current chapter content with this snapshot? A snapshot of your current content will be saved automatically.",
    restoreFailed: "Unable to restore snapshot. Try again.",
    restoreNetworkFailed: "Unable to restore snapshot — check your connection and try again.",
    restoreFailedCorrupt:
      "This snapshot is corrupt and can't be restored. It will remain in the list; create a new snapshot or restore a different one.",
    restoreFailedCrossProjectImage:
      "This snapshot references images that no longer belong to this project. It can't be restored safely.",
    restoreFailedNotFound:
      "This snapshot no longer exists. Refresh to see the latest snapshot list.",
    restoreFailedSaveFirst:
      "Unable to save pending changes. Try again once your connection recovers before restoring.",
    restoreSucceededReloadFailed:
      "Snapshot restored, but reloading the chapter failed. Refresh the page before editing — editing now would overwrite the restore.",
    restoreResponseUnreadable:
      "The restore may have completed, but the server response was unreadable. Refresh the page to see the current state — editing now could overwrite the restored content.",
    renderError: "Unable to render snapshot content",
    backToEditing: "Back to editing",
    viewingBanner: (label: string, date: string) => `Viewing snapshot: ${label} — ${date}`,
    viewingRegionLabel: "Snapshot viewing banner",
    emptyState: "No snapshots yet. Create one to save a checkpoint of your work.",
    count: (manual: number, auto: number) =>
      `${manual + auto} snapshots (${manual} manual, ${auto} auto)`,
    wordCount: (count: number) => `${count.toLocaleString()} words`,
    duplicateSkipped: "Content unchanged since last snapshot.",
    createFailed: "Unable to create snapshot. Save your unsaved changes and try again.",
    createFailedGeneric: "Unable to create snapshot. Try again.",
    deleteFailed: "Unable to delete snapshot. Try again.",
    listFailed: "Unable to load snapshots. Try opening the panel again.",
    listFailedGeneric: "Unable to load snapshots. Try again.",
    viewFailed: "Unable to open snapshot. Try again.",
    viewFailedNotFound: "This snapshot no longer exists. Refresh to see the latest snapshot list.",
    viewFailedCorrupt: "This snapshot is corrupt and can't be displayed.",
    viewFailedNetwork: "Unable to open snapshot. Check your connection and try again.",
    viewFailedSaveFirst:
      "Unable to save pending changes. Try again once your connection recovers before viewing a snapshot.",
    // I6 / S6: viewSnapshot returns {ok:true, superseded:"chapter"} when
    // the user switched chapters mid-fetch. Before I6 the click produced
    // no feedback at all (the panel's !res.ok gate ignored ok:true), so
    // the user saw a dead View button. This copy fires ONLY for the
    // actual chapter-switch case — same-chapter rapid reclicks return
    // superseded:"sameChapterNewer" and the panel stays silent (S6).
    viewStaleChapterSwitch:
      "This snapshot belongs to a different chapter. Select that chapter to view it.",
    ariaLabel: "Chapter snapshots",
    relativeTime: {
      justNow: "just now",
      minutes: (n: number) => `${n}m ago`,
      hours: (n: number) => `${n}h ago`,
      days: (n: number) => `${n}d ago`,
    },
  },
  findReplace: {
    panelTitle: "Find and Replace",
    findLabel: "Find",
    replaceLabel: "Replace",
    closeLabel: "Close",
    searching: "Searching...",
    searchPlaceholder: "Search...",
    replacePlaceholder: "Replace with...",
    matchCase: "Match case",
    wholeWord: "Whole word",
    regex: "Regular expression",
    replaceFailed: "Replace failed. Try again.",
    replaceNetworkFailed: "Replace failed — check your connection and try again.",
    replaceFailedSaveFirst:
      "Unable to save pending changes. Try again once your connection recovers before replacing.",
    replaceSucceededReloadFailed:
      "Replace succeeded, but reloading the chapter failed. Refresh the page before editing — editing now would overwrite the replacement.",
    replaceResponseUnreadable:
      "The replace may have completed, but the server response was unreadable. Refresh the page to see the current state before retrying — retrying without refreshing could replace twice.",
    replaceScopeNotFound: "The chapter for this replace is no longer available.",
    replaceProjectNotFound: "This project is no longer available.",
    searchProjectNotFound: "This project is no longer available.",
    replaceSuccess: (count: number) => `Replaced ${count} occurrence${count === 1 ? "" : "s"}.`,
    noMatches: "No matches found",
    matchCount: (count: number, chapters: number) =>
      `Found ${count} occurrence${count === 1 ? "" : "s"} in ${chapters} chapter${chapters === 1 ? "" : "s"}`,
    replaceOne: "Replace",
    replaceAllInChapter: "Replace All in Chapter",
    replaceAllInManuscript: "Replace All in Manuscript",
    replaceAllInManuscriptDelete: "Delete All in Manuscript",
    replaceConfirmTitle: "Replace across manuscript?",
    replaceChapterConfirmTitle: "Replace in chapter?",
    replaceDeleteConfirmTitle: "Delete across manuscript?",
    replaceDeleteChapterConfirmTitle: "Delete in chapter?",
    replaceConfirm: (count: number, search: string, replace: string, chapters: number) =>
      `Replace ${count} occurrence${count === 1 ? "" : "s"} of '${search}' with '${replace}' across ${chapters} chapter${chapters === 1 ? "" : "s"}? Snapshots of all affected chapters will be created automatically.`,
    replaceChapterConfirm: (count: number, search: string, replace: string) =>
      `Replace ${count} occurrence${count === 1 ? "" : "s"} of '${search}' with '${replace}' in this chapter? A snapshot will be created automatically.`,
    replaceDeleteConfirm: (count: number, search: string, chapters: number) =>
      `Delete ${count} occurrence${count === 1 ? "" : "s"} of '${search}' across ${chapters} chapter${chapters === 1 ? "" : "s"}? The replacement is empty, so every match will be removed. Snapshots of all affected chapters will be created automatically.`,
    replaceDeleteChapterConfirm: (count: number, search: string) =>
      `Delete ${count} occurrence${count === 1 ? "" : "s"} of '${search}' in this chapter? The replacement is empty, so every match will be removed. A snapshot will be created automatically.`,
    replaceConfirmButton: "Replace All",
    replaceDeleteConfirmButton: "Delete All",
    replaceCancelButton: "Cancel",
    matchNotFound: "Match no longer found — try searching again.",
    invalidRegex: "Invalid regular expression",
    tooManyMatches: "Too many matches — refine your search and try again.",
    searchTimedOut: "Search timed out — refine your pattern and try again.",
    contentTooLarge:
      "Replacement would produce chapter content over the size limit; refine your replacement.",
    invalidReplaceRequest: "Replace request was rejected. Check your search and replace inputs.",
    invalidSearchRequest: "Search request was rejected. Check your search input.",
    searchFailed: "Search failed. Try again.",
    searchNetworkFailed: "Search failed — check your connection and try again.",
    skippedChapters: (count: number) =>
      `${count} chapter${count === 1 ? " was" : "s were"} skipped due to corrupt content.`,
    skippedAfterReplace: (count: number) =>
      `Replace completed, but ${count} chapter${count === 1 ? " was" : "s were"} skipped due to corrupt content.`,
    chapterMatches: (title: string, count: number) =>
      `${title} (${count} match${count === 1 ? "" : "es"})`,
    ariaLabel: "Find and replace",
    toggleTooltip: "Find and replace (Ctrl+H)",
  },
} as const;
